sonar.projectKey=RobelManoa_urbanhub-ms-validateur
sonar.projectName=MS Validateur
sonar.organization=robelmanoa
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=report_tests.xml
sonar.python.flake8.reportPaths=reports/quality/flake8_apres.txt
